# Project 6 EDA Notebook
**Author:** Abdelhafidh Mahouel  
**Date:** 2026-02-16  
**Purpose:** Exploratory Data Analysis (EDA) on a selected dataset to discover patterns and communicate insights using tables and visualizations.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset("penguins")
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [3]:
row_count = df.shape[0]
col_count = df.shape[1]
columns = list(df.columns)

row_count, col_count, columns

(344,
 7,
 ['species',
  'island',
  'bill_length_mm',
  'bill_depth_mm',
  'flipper_length_mm',
  'body_mass_g',
  'sex'])

In [4]:
pd.DataFrame({"column": df.columns, "dtype": df.dtypes.astype(str)} )

                              column    dtype
species                      species      str
island                        island      str
bill_length_mm        bill_length_mm  float64
bill_depth_mm          bill_depth_mm  float64
flipper_length_mm  flipper_length_mm  float64
body_mass_g              body_mass_g  float64
sex                              sex      str

In [5]:
df.shape[0]

344